### PR TITLE
Disallow wrangler-transform from working with cdap-data-pipeline-4.2.

### PR DESCRIPTION
**Pull request by anwar6953**
wrangler-transform isn't compatible with cdap-data-pipeline-4.2.0. Without this change, and upgrade of CDAP will result in the following error in master logs:

```
2017-08-24 00:24:31,054 - WARN  [Endure-Service-:c.c.c.i.a.r.a.DefaultArtifactRepository@421] - Could not add system artifact ‘wrangler-transform-3.0.0-SNAPSHOT.jar’ because it is invalid.
co.cask.cdap.common.InvalidArtifactException: Class could not be found while inspecting artifact for plugins. Please check dependencies are available, and that the correct parent ar
tifact was specified. Error class: class java.lang.NoClassDefFoundError, message: co/cask/cdap/etl/api/StageSubmitterContext.
        at co.cask.cdap.internal.app.runtime.artifact.ArtifactInspector.inspectPlugins(ArtifactInspector.java:253) ~[na:na]
        at co.cask.cdap.internal.app.runtime.artifact.ArtifactInspector.inspectArtifact(ArtifactInspector.java:137) ~[na:na]
        at co.cask.cdap.internal.app.runtime.artifact.DefaultArtifactRepository.inspectArtifact(DefaultArtifactRepository.java:431) [na:na]
        at co.cask.cdap.internal.app.runtime.artifact.DefaultArtifactRepository.addArtifact(DefaultArtifactRepository.java:242) [na:na]
        at co.cask.cdap.internal.app.runtime.artifact.DefaultArtifactRepository.addSystemArtifact(DefaultArtifactRepository.java:410) [na:na]
        at co.cask.cdap.internal.app.runtime.artifact.DefaultArtifactRepository.addSystemArtifacts(DefaultArtifactRepository.java:366) [na:na]
        at co.cask.cdap.internal.app.runtime.artifact.AuthorizationArtifactRepository.addSystemArtifacts(AuthorizationArtifactRepository.java:243) [na:na]
        at co.cask.cdap.internal.app.runtime.artifact.SystemArtifactLoader$1$1.doStart(SystemArtifactLoader.java:50) [na:na]
        at com.google.common.util.concurrent.AbstractService.start(AbstractService.java:170) [com.google.guava.guava-13.0.1.jar:na]
        at co.cask.cdap.common.service.RetryOnStartFailureService$1.run(RetryOnStartFailureService.java:73) [na:na]
Caused by: java.lang.NoClassDefFoundError: co/cask/cdap/etl/api/StageSubmitterContext
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_131]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_131]
        at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[na:1.8.0_131]
        at java.lang.Class.getMethods(Class.java:1615) ~[na:1.8.0_131]
        at co.cask.cdap.internal.app.runtime.artifact.ArtifactInspector.getPluginEndpoints(ArtifactInspector.java:360) ~[na:na]
        at co.cask.cdap.internal.app.runtime.artifact.ArtifactInspector.inspectPlugins(ArtifactInspector.java:243) ~[na:na]
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: co.cask.cdap.etl.api.StageSubmitterContext
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
        at co.cask.cdap.common.lang.InterceptableClassLoader.findClass(InterceptableClassLoader.java:46) ~[na:na]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
        ... 15 common frames omitted
```

### CODE REVIEW

**Review by albertshau — APPROVED** [review]
lgtm
